name: Build and Publish Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Notify webhook (trigger redeploy)
      run: |
        curl -X POST ${{ secrets.DEPLOY_WEBHOOK_URL }}
